{% set name = "pandapower" %}
{% set version = "2.14.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: c184eaf364f8c1da100add796c856c3df543873e5d78c6092e6d9674707cbb30

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - deepdiff
    - networkx >=2.5
    - numpy <2.0
    - packaging
    - pandas >=1.0
    - scipy
    - tqdm

test:
  imports:
    - pandapower
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
