{% set name = "pandapower" %}
{% set version = "2.14.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: d193499f5ef1100d12b104c9e25cd025bb69d78a6c95b1ab5628b289c0852a8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - deepdiff
    - networkx >=2.5
    - numpy <2.0
    - packaging
    - pandas >=1.0
    - scipy
    - tqdm

test:
  imports:
    - pandapower
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
