{% set name = "pandapower" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: 75f8a2fa8c5a7f46b6f75ef320fb37f5e2c200a585cf09a5f352c64a88e6d7c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - cryptography
    - networkx
    - numba
    - numpy >=0.11
    - openpyxl
    - packaging
    - pandas >=0.17
    - python
    - scipy
    - xlrd
    - xlsxwriter

test:
  imports:
    - pandapower
    - pandapower.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
