{% set name = "pandapower" %}
{% set version = "2.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: 66ddd54b306c7d49fd54f1e8641948b1a9a890a2133d9d5c3e72a269ca4ce9dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - deepdiff
    - networkx >=2.5
    - numpy
    - packaging
    - pandas >=1.0
    - scipy
    - tqdm

test:
  imports:
    - pandapower
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
