{% set name = "pandapower" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01d697460e0a1342f578e8751bfa0181c6fccea9322fac4b7f69298bdd6c0203

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - deepdiff
    - networkx >=2.5
    - numpy <2.0
    - packaging
    - pandas >=1.0
    - scipy
    - tqdm

test:
  imports:
    - pandapower
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
